export enum TimezoneStrings {
  "Africa/Abidjan",
  "Africa/Algiers",
  "Africa/Bamako",
  "Africa/Bissau",
  "Africa/Cairo",
  "Africa/Casablanca",
  "Africa/Ceuta",
  "Africa/El_Aaiun",
  "Africa/Johannesburg",
  "Africa/Juba",
  "Africa/Khartoum",
  "Africa/Lagos",
  "Africa/Malabo",
  "Africa/Maputo",
  "Africa/Monrovia",
  "Africa/Nairobi",
  "Africa/Ndjamena",
  "Africa/Sao_Tome",
  "Africa/Tripoli",
  "Africa/Tunis",
  "Africa/Windhoek",
  "America/Adak",
  "America/Anchorage",
  "America/Araguaina",
  "America/Argentina/Buenos_Aires",
  "America/Argentina/Catamarca",
  "America/Argentina/Cordoba",
  "America/Argentina/Jujuy",
  "America/Argentina/La_Rioja",
  "America/Argentina/Mendoza",
  "America/Argentina/Rio_Gallegos",
  "America/Argentina/Salta",
  "America/Argentina/San_Juan",
  "America/Argentina/San_Luis",
  "America/Argentina/Tucuman",
  "America/Argentina/Ushuaia",
  "America/Aruba",
  "America/Asuncion",
  "America/Atikokan",
  "America/Bahia",
  "America/Bahia_Banderas",
  "America/Barbados",
  "America/Belem",
  "America/Belize",
  "America/Blanc-Sablon",
  "America/Boa_Vista",
  "America/Bogota",
  "America/Boise",
  "America/Cambridge_Bay",
  "America/Campo_Grande",
  "America/Cancun",
  "America/Caracas",
  "America/Cayenne",
  "America/Cayman",
  "America/Chicago",
  "America/Chihuahua",
  "America/Costa_Rica",
  "America/Creston",
  "America/Cuiaba",
  "America/Curacao",
  "America/Danmarkshavn",
  "America/Dawson",
  "America/Dawson_Creek",
  "America/Denver",
  "America/Detroit",
  "America/Dominica",
  "America/Edmonton",
  "America/Eirunepe",
  "America/El_Salvador",
  "America/Fort_Nelson",
  "America/Fortaleza",
  "America/Glace_Bay",
  "America/Godthab",
  "America/Goose_Bay",
  "America/Grand_Turk",
  "America/Grenada",
  "America/Guadeloupe",
  "America/Guatemala",
  "America/Guayaquil",
  "America/Guyana",
  "America/Halifax",
  "America/Havana",
  "America/Hermosillo",
  "America/Indiana/Indianapolis",
  "America/Indiana/Knox",
  "America/Indiana/Marengo",
  "America/Indiana/Petersburg",
  "America/Indiana/Tell_City",
  "America/Indiana/Vevay",
  "America/Indiana/Vincennes",
  "America/Indiana/Winamac",
  "America/Inuvik",
  "America/Iqaluit",
  "America/Jamaica",
  "America/Juneau",
  "America/Kentucky/Louisville",
  "America/Kentucky/Monticello",
  "America/La_Paz",
  "America/Lima",
  "America/Los_Angeles",
  "America/Lower_Princes",
  "America/Maceio",
  "America/Managua",
  "America/Manaus",
  "America/Marigot",
  "America/Martinique",
  "America/Matamoros",
  "America/Mazatlan",
  "America/Menominee",
  "America/Merida",
  "America/Metlakatla",
  "America/Mexico_City",
  "America/Miquelon",
  "America/Moncton",
  "America/Monterrey",
  "America/Montevideo",
  "America/Montserrat",
  "America/Nassau",
  "America/New_York",
  "America/Nipigon",
  "America/Nome",
  "America/Noronha",
  "America/North_Dakota/Beulah",
  "America/North_Dakota/Center",
  "America/North_Dakota/New_Salem",
  "America/Ojinaga",
  "America/Panama",
  "America/Pangnirtung",
  "America/Paramaribo",
  "America/Phoenix",
  "America/Port_of_Spain",
  "America/Port-au-Prince",
  "America/Porto_Velho",
  "America/Puerto_Rico",
  "America/Rainy_River",
  "America/Rankin_Inlet",
  "America/Recife",
  "America/Regina",
  "America/Resolute",
  "America/Rio_Branco",
  "America/Santarem",
  "America/Santiago",
  "America/Santo_Domingo",
  "America/Sao_Paulo",
  "America/Scoresbysund",
  "America/Sitka",
  "America/St_Barthelemy",
  "America/St_Johns",
  "America/St_Kitts",
  "America/St_Lucia",
  "America/St_Thomas",
  "America/St_Vincent",
  "America/Swift_Current",
  "America/Tegucigalpa",
  "America/Thule",
  "America/Thunder_Bay",
  "America/Tijuana",
  "America/Toronto",
  "America/Tortola",
  "America/Vancouver",
  "America/Whitehorse",
  "America/Winnipeg",
  "America/Yakutat",
  "America/Yellowknife",
  "Antarctica/Casey",
  "Antarctica/Davis",
  "Antarctica/DumontDUrville",
  "Antarctica/Macquarie",
  "Antarctica/Mawson",
  "Antarctica/McMurdo",
  "Antarctica/Palmer",
  "Antarctica/Rothera",
  "Antarctica/Syowa",
  "Antarctica/Troll",
  "Antarctica/Vostok",
  "Arctic/Longyearbyen",
  "Asia/Aden",
  "Asia/Almaty",
  "Asia/Amman",
  "Asia/Anadyr",
  "Asia/Aqtau",
  "Asia/Aqtobe",
  "Asia/Ashgabat",
  "Asia/Baghdad",
  "Asia/Bahrain",
  "Asia/Baku",
  "Asia/Bangkok",
  "Asia/Barnaul",
  "Asia/Beirut",
  "Asia/Bishkek",
  "Asia/Brunei",
  "Asia/Chita",
  "Asia/Choibalsan",
  "Asia/Colombo",
  "Asia/Damascus",
  "Asia/Dhaka",
  "Asia/Dili",
  "Asia/Dubai",
  "Asia/Dushanbe",
  "Asia/Gaza",
  "Asia/Hebron",
  "Asia/Ho_Chi_Minh",
  "Asia/Hong_Kong",
  "Asia/Hovd",
  "Asia/Irkutsk",
  "Asia/Jakarta",
  "Asia/Jayapura",
  "Asia/Jerusalem",
  "Asia/Kabul",
  "Asia/Kamchatka",
  "Asia/Karachi",
  "Asia/Kathmandu",
  "Asia/Khandyga",
  "Asia/Kolkata",
  "Asia/Krasnoyarsk",
  "Asia/Kuala_Lumpur",
  "Asia/Kuching",
  "Asia/Kuwait",
  "Asia/Macau",
  "Asia/Magadan",
  "Asia/Makassar",
  "Asia/Manila",
  "Asia/Muscat",
  "Asia/Nicosia",
  "Asia/Novokuznetsk",
  "Asia/Novosibirsk",
  "Asia/Omsk",
  "Asia/Oral",
  "Asia/Phnom_Penh",
  "Asia/Pontianak",
  "Asia/Pyongyang",
  "Asia/Qatar",
  "Asia/Qyzylorda",
  "Asia/Rangoon",
  "Asia/Riyadh",
  "Asia/Sakhalin",
  "Asia/Samarkand",
  "Asia/Seoul",
  "Asia/Shanghai",
  "Asia/Singapore",
  "Asia/Srednekolymsk",
  "Asia/Taipei",
  "Asia/Tashkent",
  "Asia/Tbilisi",
  "Asia/Tehran",
  "Asia/Thimphu",
  "Asia/Tokyo",
  "Asia/Tomsk",
  "Asia/Ulaanbaatar",
  "Asia/Urumqi",
  "Asia/Ust-Nera",
  "Asia/Vientiane",
  "Asia/Vladivostok",
  "Asia/Yakutsk",
  "Asia/Yekaterinburg",
  "Asia/Yerevan",
  "Atlantic/Azores",
  "Atlantic/Bermuda",
  "Atlantic/Canary",
  "Atlantic/Cape_Verde",
  "Atlantic/Faroe",
  "Atlantic/Madeira",
  "Atlantic/Reykjavik",
  "Atlantic/South_Georgia",
  "Atlantic/Stanley",
  "Australia/Adelaide",
  "Australia/Brisbane",
  "Australia/Broken_Hill",
  "Australia/Currie",
  "Australia/Darwin",
  "Australia/Eucla",
  "Australia/Hobart",
  "Australia/Lindeman",
  "Australia/Lord_Howe",
  "Australia/Melbourne",
  "Australia/Perth",
  "Australia/Sydney",
  "Europe/Amsterdam",
  "Europe/Andorra",
  "Europe/Astrakhan",
  "Europe/Athens",
  "Europe/Belgrade",
  "Europe/Berlin",
  "Europe/Bratislava",
  "Europe/Brussels",
  "Europe/Bucharest",
  "Europe/Budapest",
  "Europe/Busingen",
  "Europe/Chisinau",
  "Europe/Copenhagen",
  "Europe/Dublin",
  "Europe/Gibraltar",
  "Europe/Guernsey",
  "Europe/Helsinki",
  "Europe/Isle_of_Man",
  "Europe/Istanbul",
  "Europe/Jersey",
  "Europe/Kaliningrad",
  "Europe/Kiev",
  "Europe/Kirov",
  "Europe/Lisbon",
  "Europe/Ljubljana",
  "Europe/London",
  "Europe/Luxembourg",
  "Europe/Madrid",
  "Europe/Malta",
  "Europe/Mariehamn",
  "Europe/Minsk",
  "Europe/Monaco",
  "Europe/Moscow",
  "Europe/Oslo",
  "Europe/Paris",
  "Europe/Podgorica",
  "Europe/Prague",
  "Europe/Riga",
  "Europe/Rome",
  "Europe/Samara",
  "Europe/San_Marino",
  "Europe/Sarajevo",
  "Europe/Simferopol",
  "Europe/Skopje",
  "Europe/Sofia",
  "Europe/Stockholm",
  "Europe/Tallinn",
  "Europe/Tirane",
  "Europe/Ulyanovsk",
  "Europe/Uzhgorod",
  "Europe/Vaduz",
  "Europe/Vatican",
  "Europe/Vienna",
  "Europe/Vilnius",
  "Europe/Volgograd",
  "Europe/Warsaw",
  "Europe/Zagreb",
  "Europe/Zaporozhye",
  "Europe/Zurich",
  "Indian/Antananarivo",
  "Indian/Chagos",
  "Indian/Christmas",
  "Indian/Cocos",
  "Indian/Comoro",
  "Indian/Kerguelen",
  "Indian/Mahe",
  "Indian/Maldives",
  "Indian/Mauritius",
  "Indian/Mayotte",
  "Indian/Reunion",
  "Pacific/Apia",
  "Pacific/Auckland",
  "Pacific/Bougainville",
  "Pacific/Chatham",
  "Pacific/Chuuk",
  "Pacific/Easter",
  "Pacific/Efate",
  "Pacific/Enderbury",
  "Pacific/Fakaofo",
  "Pacific/Fiji",
  "Pacific/Funafuti",
  "Pacific/Galapagos",
  "Pacific/Gambier",
  "Pacific/Guadalcanal",
  "Pacific/Guam",
  "Pacific/Honolulu",
  "Pacific/Johnston",
  "Pacific/Kiritimati",
  "Pacific/Kosrae",
  "Pacific/Kwajalein",
  "Pacific/Majuro",
  "Pacific/Marquesas",
  "Pacific/Midway",
  "Pacific/Nauru",
  "Pacific/Niue",
  "Pacific/Norfolk",
  "Pacific/Noumea",
  "Pacific/Pago_Pago",
  "Pacific/Palau",
  "Pacific/Pitcairn",
  "Pacific/Pohnpei",
  "Pacific/Port_Moresby",
  "Pacific/Rarotonga",
  "Pacific/Saipan",
  "Pacific/Tahiti",
  "Pacific/Tarawa",
  "Pacific/Tongatapu",
  "Pacific/Wake",
  "Pacific/Wallis"
}

export enum TZTimezones {
  abidjan = TimezoneStrings["Africa/Abidjan"],
  algiers = TimezoneStrings["Africa/Algiers"],
  bamako = TimezoneStrings["Africa/Bamako"],
  bissau = TimezoneStrings["Africa/Bissau"],
  cairo = TimezoneStrings["Africa/Cairo"],
  casablanca = TimezoneStrings["Africa/Casablanca"],
  ceuta = TimezoneStrings["Africa/Ceuta"],
  el_aaiun = TimezoneStrings["Africa/El_Aaiun"],
  johannesburg = TimezoneStrings["Africa/Johannesburg"],
  juba = TimezoneStrings["Africa/Juba"],
  khartoum = TimezoneStrings["Africa/Khartoum"],
  lagos = TimezoneStrings["Africa/Lagos"],
  malabo = TimezoneStrings["Africa/Malabo"],
  maputo = TimezoneStrings["Africa/Maputo"],
  monrovia = TimezoneStrings["Africa/Monrovia"],
  nairobi = TimezoneStrings["Africa/Nairobi"],
  ndjamena = TimezoneStrings["Africa/Ndjamena"],
  sao_tome = TimezoneStrings["Africa/Sao_Tome"],
  tripoli = TimezoneStrings["Africa/Tripoli"],
  tunis = TimezoneStrings["Africa/Tunis"],
  windhoek = TimezoneStrings["Africa/Windhoek"],
  adak = TimezoneStrings["America/Adak"],
  anchorage = TimezoneStrings["America/Anchorage"],
  araguaina = TimezoneStrings["America/Araguaina"],
  buenos_aires = TimezoneStrings["America/Argentina/Buenos_Aires"],
  catamarca = TimezoneStrings["America/Argentina/Catamarca"],
  cordoba = TimezoneStrings["America/Argentina/Cordoba"],
  jujuy = TimezoneStrings["America/Argentina/Jujuy"],
  la_rioja = TimezoneStrings["America/Argentina/La_Rioja"],
  mendoza = TimezoneStrings["America/Argentina/Mendoza"],
  rio_gallegos = TimezoneStrings["America/Argentina/Rio_Gallegos"],
  salta = TimezoneStrings["America/Argentina/Salta"],
  san_juan = TimezoneStrings["America/Argentina/San_Juan"],
  san_luis = TimezoneStrings["America/Argentina/San_Luis"],
  tucuman = TimezoneStrings["America/Argentina/Tucuman"],
  ushuaia = TimezoneStrings["America/Argentina/Ushuaia"],
  aruba = TimezoneStrings["America/Aruba"],
  asuncion = TimezoneStrings["America/Asuncion"],
  atikokan = TimezoneStrings["America/Atikokan"],
  bahia = TimezoneStrings["America/Bahia"],
  bahia_banderas = TimezoneStrings["America/Bahia_Banderas"],
  barbados = TimezoneStrings["America/Barbados"],
  belem = TimezoneStrings["America/Belem"],
  belize = TimezoneStrings["America/Belize"],
  blanc_sablon = TimezoneStrings["America/Blanc-Sablon"],
  boa_vista = TimezoneStrings["America/Boa_Vista"],
  bogota = TimezoneStrings["America/Bogota"],
  boise = TimezoneStrings["America/Boise"],
  cambridge_bay = TimezoneStrings["America/Cambridge_Bay"],
  campo_grande = TimezoneStrings["America/Campo_Grande"],
  cancun = TimezoneStrings["America/Cancun"],
  caracas = TimezoneStrings["America/Caracas"],
  cayenne = TimezoneStrings["America/Cayenne"],
  cayman = TimezoneStrings["America/Cayman"],
  chicago = TimezoneStrings["America/Chicago"],
  chihuahua = TimezoneStrings["America/Chihuahua"],
  costa_rica = TimezoneStrings["America/Costa_Rica"],
  creston = TimezoneStrings["America/Creston"],
  cuiaba = TimezoneStrings["America/Cuiaba"],
  curacao = TimezoneStrings["America/Curacao"],
  danmarkshavn = TimezoneStrings["America/Danmarkshavn"],
  dawson = TimezoneStrings["America/Dawson"],
  dawson_creek = TimezoneStrings["America/Dawson_Creek"],
  denver = TimezoneStrings["America/Denver"],
  detroit = TimezoneStrings["America/Detroit"],
  dominica = TimezoneStrings["America/Dominica"],
  edmonton = TimezoneStrings["America/Edmonton"],
  eirunepe = TimezoneStrings["America/Eirunepe"],
  el_salvador = TimezoneStrings["America/El_Salvador"],
  fort_nelson = TimezoneStrings["America/Fort_Nelson"],
  fortaleza = TimezoneStrings["America/Fortaleza"],
  glace_bay = TimezoneStrings["America/Glace_Bay"],
  godthab = TimezoneStrings["America/Godthab"],
  goose_bay = TimezoneStrings["America/Goose_Bay"],
  grand_turk = TimezoneStrings["America/Grand_Turk"],
  grenada = TimezoneStrings["America/Grenada"],
  guadeloupe = TimezoneStrings["America/Guadeloupe"],
  guatemala = TimezoneStrings["America/Guatemala"],
  guayaquil = TimezoneStrings["America/Guayaquil"],
  guyana = TimezoneStrings["America/Guyana"],
  halifax = TimezoneStrings["America/Halifax"],
  havana = TimezoneStrings["America/Havana"],
  hermosillo = TimezoneStrings["America/Hermosillo"],
  indianapolis = TimezoneStrings["America/Indiana/Indianapolis"],
  knox = TimezoneStrings["America/Indiana/Knox"],
  marengo = TimezoneStrings["America/Indiana/Marengo"],
  petersburg = TimezoneStrings["America/Indiana/Petersburg"],
  tell_city = TimezoneStrings["America/Indiana/Tell_City"],
  vevey = TimezoneStrings["America/Indiana/Vevay"],
  vincennes = TimezoneStrings["America/Indiana/Vincennes"],
  winamac = TimezoneStrings["America/Indiana/Winamac"],
  inuvik = TimezoneStrings["America/Inuvik"],
  iqaluit = TimezoneStrings["America/Iqaluit"],
  jamaica = TimezoneStrings["America/Jamaica"],
  juneau = TimezoneStrings["America/Juneau"],
  louisville = TimezoneStrings["America/Kentucky/Louisville"],
  monticello = TimezoneStrings["America/Kentucky/Monticello"],
  la_paz = TimezoneStrings["America/La_Paz"],
  lima = TimezoneStrings["America/Lima"],
  los_angeles = TimezoneStrings["America/Los_Angeles"],
  lower_princes = TimezoneStrings["America/Lower_Princes"],
  maceio = TimezoneStrings["America/Maceio"],
  managua = TimezoneStrings["America/Managua"],
  manaus = TimezoneStrings["America/Manaus"],
  marigot = TimezoneStrings["America/Marigot"],
  martinique = TimezoneStrings["America/Martinique"],
  matamoros = TimezoneStrings["America/Matamoros"],
  mazatlan = TimezoneStrings["America/Mazatlan"],
  menominee = TimezoneStrings["America/Menominee"],
  merida = TimezoneStrings["America/Merida"],
  metlakatla = TimezoneStrings["America/Metlakatla"],
  mexico_city = TimezoneStrings["America/Mexico_City"],
  miquelon = TimezoneStrings["America/Miquelon"],
  moncton = TimezoneStrings["America/Moncton"],
  monterrey = TimezoneStrings["America/Monterrey"],
  montevideo = TimezoneStrings["America/Montevideo"],
  montserrat = TimezoneStrings["America/Montserrat"],
  nassau = TimezoneStrings["America/Nassau"],
  new_york = TimezoneStrings["America/New_York"],
  nipigon = TimezoneStrings["America/Nipigon"],
  nome = TimezoneStrings["America/Nome"],
  noronha = TimezoneStrings["America/Noronha"],
  beulah = TimezoneStrings["America/North_Dakota/Beulah"],
  center = TimezoneStrings["America/North_Dakota/Center"],
  new_salem = TimezoneStrings["America/North_Dakota/New_Salem"],
  ojinaga = TimezoneStrings["America/Ojinaga"],
  panama = TimezoneStrings["America/Panama"],
  pangnirtung = TimezoneStrings["America/Pangnirtung"],
  paramaribo = TimezoneStrings["America/Paramaribo"],
  phoenix = TimezoneStrings["America/Phoenix"],
  port_of_spain = TimezoneStrings["America/Port_of_Spain"],
  port_au_prince = TimezoneStrings["America/Port-au-Prince"],
  porto_velho = TimezoneStrings["America/Porto_Velho"],
  puerto_rico = TimezoneStrings["America/Puerto_Rico"],
  rainy_river = TimezoneStrings["America/Rainy_River"],
  rankin_inlet = TimezoneStrings["America/Rankin_Inlet"],
  recife = TimezoneStrings["America/Recife"],
  regina = TimezoneStrings["America/Regina"],
  resolute = TimezoneStrings["America/Resolute"],
  rio_branco = TimezoneStrings["America/Rio_Branco"],
  santarem = TimezoneStrings["America/Santarem"],
  santiago = TimezoneStrings["America/Santiago"],
  santo_domingo = TimezoneStrings["America/Santo_Domingo"],
  sao_paulo = TimezoneStrings["America/Sao_Paulo"],
  scoresbysund = TimezoneStrings["America/Scoresbysund"],
  sitka = TimezoneStrings["America/Sitka"],
  st_barthelemy = TimezoneStrings["America/St_Barthelemy"],
  st_johns = TimezoneStrings["America/St_Johns"],
  st_kitts = TimezoneStrings["America/St_Kitts"],
  st_lucia = TimezoneStrings["America/St_Lucia"],
  st_thomas = TimezoneStrings["America/St_Thomas"],
  st_vincent = TimezoneStrings["America/St_Vincent"],
  swift_current = TimezoneStrings["America/Swift_Current"],
  tegucigalpa = TimezoneStrings["America/Tegucigalpa"],
  thule = TimezoneStrings["America/Thule"],
  thunder_bay = TimezoneStrings["America/Thunder_Bay"],
  tijuana = TimezoneStrings["America/Tijuana"],
  toronto = TimezoneStrings["America/Toronto"],
  tortola = TimezoneStrings["America/Tortola"],
  vancouver = TimezoneStrings["America/Vancouver"],
  whitehorse = TimezoneStrings["America/Whitehorse"],
  winnipeg = TimezoneStrings["America/Winnipeg"],
  yakutat = TimezoneStrings["America/Yakutat"],
  yellowknife = TimezoneStrings["America/Yellowknife"],
  casey = TimezoneStrings["Antarctica/Casey"],
  davis = TimezoneStrings["Antarctica/Davis"],
  dumontdurville = TimezoneStrings["Antarctica/DumontDUrville"],
  macquarie = TimezoneStrings["Antarctica/Macquarie"],
  mawson = TimezoneStrings["Antarctica/Mawson"],
  mcmurdo = TimezoneStrings["Antarctica/McMurdo"],
  palmer = TimezoneStrings["Antarctica/Palmer"],
  rothera = TimezoneStrings["Antarctica/Rothera"],
  syowa = TimezoneStrings["Antarctica/Syowa"],
  troll = TimezoneStrings["Antarctica/Troll"],
  vostok = TimezoneStrings["Antarctica/Vostok"],
  longyearbyen = TimezoneStrings["Arctic/Longyearbyen"],
  aden = TimezoneStrings["Asia/Aden"],
  almaty = TimezoneStrings["Asia/Almaty"],
  amman = TimezoneStrings["Asia/Amman"],
  anadyr = TimezoneStrings["Asia/Anadyr"],
  aqtau = TimezoneStrings["Asia/Aqtau"],
  aqtobe = TimezoneStrings["Asia/Aqtobe"],
  ashgabat = TimezoneStrings["Asia/Ashgabat"],
  baghdad = TimezoneStrings["Asia/Baghdad"],
  bahrain = TimezoneStrings["Asia/Bahrain"],
  baku = TimezoneStrings["Asia/Baku"],
  bangkok = TimezoneStrings["Asia/Bangkok"],
  barnaul = TimezoneStrings["Asia/Barnaul"],
  beirut = TimezoneStrings["Asia/Beirut"],
  bishkek = TimezoneStrings["Asia/Bishkek"],
  brunei = TimezoneStrings["Asia/Brunei"],
  chita = TimezoneStrings["Asia/Chita"],
  choibalsan = TimezoneStrings["Asia/Choibalsan"],
  colombo = TimezoneStrings["Asia/Colombo"],
  damascus = TimezoneStrings["Asia/Damascus"],
  dhaka = TimezoneStrings["Asia/Dhaka"],
  dili = TimezoneStrings["Asia/Dili"],
  dubai = TimezoneStrings["Asia/Dubai"],
  dushanbe = TimezoneStrings["Asia/Dushanbe"],
  gaza = TimezoneStrings["Asia/Gaza"],
  hebron = TimezoneStrings["Asia/Hebron"],
  ho_chi_minh = TimezoneStrings["Asia/Ho_Chi_Minh"],
  hong_kong = TimezoneStrings["Asia/Hong_Kong"],
  hovd = TimezoneStrings["Asia/Hovd"],
  irkutsk = TimezoneStrings["Asia/Irkutsk"],
  jakarta = TimezoneStrings["Asia/Jakarta"],
  jayapura = TimezoneStrings["Asia/Jayapura"],
  jerusalem = TimezoneStrings["Asia/Jerusalem"],
  kabul = TimezoneStrings["Asia/Kabul"],
  kamchatka = TimezoneStrings["Asia/Kamchatka"],
  karachi = TimezoneStrings["Asia/Karachi"],
  kathmandu = TimezoneStrings["Asia/Kathmandu"],
  khandyga = TimezoneStrings["Asia/Khandyga"],
  kolkata = TimezoneStrings["Asia/Kolkata"],
  krasnoyarsk = TimezoneStrings["Asia/Krasnoyarsk"],
  kuala_lumpur = TimezoneStrings["Asia/Kuala_Lumpur"],
  kuching = TimezoneStrings["Asia/Kuching"],
  kuwait = TimezoneStrings["Asia/Kuwait"],
  macau = TimezoneStrings["Asia/Macau"],
  magadan = TimezoneStrings["Asia/Magadan"],
  makassar = TimezoneStrings["Asia/Makassar"],
  manila = TimezoneStrings["Asia/Manila"],
  muscat = TimezoneStrings["Asia/Muscat"],
  nicosia = TimezoneStrings["Asia/Nicosia"],
  novokuznetsk = TimezoneStrings["Asia/Novokuznetsk"],
  novosibirsk = TimezoneStrings["Asia/Novosibirsk"],
  omsk = TimezoneStrings["Asia/Omsk"],
  oral = TimezoneStrings["Asia/Oral"],
  phnom_penh = TimezoneStrings["Asia/Phnom_Penh"],
  pontianak = TimezoneStrings["Asia/Pontianak"],
  pyongyang = TimezoneStrings["Asia/Pyongyang"],
  qatar = TimezoneStrings["Asia/Qatar"],
  qyzylorda = TimezoneStrings["Asia/Qyzylorda"],
  rangoon = TimezoneStrings["Asia/Rangoon"],
  riyadh = TimezoneStrings["Asia/Riyadh"],
  sakhalin = TimezoneStrings["Asia/Sakhalin"],
  samarkand = TimezoneStrings["Asia/Samarkand"],
  seoul = TimezoneStrings["Asia/Seoul"],
  shanghai = TimezoneStrings["Asia/Shanghai"],
  singapore = TimezoneStrings["Asia/Singapore"],
  srednekolymsk = TimezoneStrings["Asia/Srednekolymsk"],
  taipei = TimezoneStrings["Asia/Taipei"],
  tashkent = TimezoneStrings["Asia/Tashkent"],
  tbilisi = TimezoneStrings["Asia/Tbilisi"],
  tehran = TimezoneStrings["Asia/Tehran"],
  thimphu = TimezoneStrings["Asia/Thimphu"],
  tokyo = TimezoneStrings["Asia/Tokyo"],
  tomsk = TimezoneStrings["Asia/Tomsk"],
  ulaanbaatar = TimezoneStrings["Asia/Ulaanbaatar"],
  urumqi = TimezoneStrings["Asia/Urumqi"],
  ust_nera = TimezoneStrings["Asia/Ust-Nera"],
  vientiane = TimezoneStrings["Asia/Vientiane"],
  vladivostok = TimezoneStrings["Asia/Vladivostok"],
  yakutsk = TimezoneStrings["Asia/Yakutsk"],
  yekaterinburg = TimezoneStrings["Asia/Yekaterinburg"],
  yerevan = TimezoneStrings["Asia/Yerevan"],
  azores = TimezoneStrings["Atlantic/Azores"],
  bermuda = TimezoneStrings["Atlantic/Bermuda"],
  canary = TimezoneStrings["Atlantic/Canary"],
  cape_verde = TimezoneStrings["Atlantic/Cape_Verde"],
  faroe = TimezoneStrings["Atlantic/Faroe"],
  madeira = TimezoneStrings["Atlantic/Madeira"],
  reykjavik = TimezoneStrings["Atlantic/Reykjavik"],
  south_georgia = TimezoneStrings["Atlantic/South_Georgia"],
  stanley = TimezoneStrings["Atlantic/Stanley"],
  adelaide = TimezoneStrings["Australia/Adelaide"],
  brisbane = TimezoneStrings["Australia/Brisbane"],
  broken_hill = TimezoneStrings["Australia/Broken_Hill"],
  currie = TimezoneStrings["Australia/Currie"],
  darwin = TimezoneStrings["Australia/Darwin"],
  eucla = TimezoneStrings["Australia/Eucla"],
  hobart = TimezoneStrings["Australia/Hobart"],
  lindeman = TimezoneStrings["Australia/Lindeman"],
  lord_howe = TimezoneStrings["Australia/Lord_Howe"],
  melbourne = TimezoneStrings["Australia/Melbourne"],
  perth = TimezoneStrings["Australia/Perth"],
  sydney = TimezoneStrings["Australia/Sydney"],
  amsterdam = TimezoneStrings["Europe/Amsterdam"],
  andorra = TimezoneStrings["Europe/Andorra"],
  astrakhan = TimezoneStrings["Europe/Astrakhan"],
  athens = TimezoneStrings["Europe/Athens"],
  belgrade = TimezoneStrings["Europe/Belgrade"],
  berlin = TimezoneStrings["Europe/Berlin"],
  bratislava = TimezoneStrings["Europe/Bratislava"],
  brussels = TimezoneStrings["Europe/Brussels"],
  bucharest = TimezoneStrings["Europe/Bucharest"],
  budapest = TimezoneStrings["Europe/Budapest"],
  busingen = TimezoneStrings["Europe/Busingen"],
  chisinau = TimezoneStrings["Europe/Chisinau"],
  copenhagen = TimezoneStrings["Europe/Copenhagen"],
  dublin = TimezoneStrings["Europe/Dublin"],
  gibraltar = TimezoneStrings["Europe/Gibraltar"],
  guernsey = TimezoneStrings["Europe/Guernsey"],
  helsinki = TimezoneStrings["Europe/Helsinki"],
  isle_of_man = TimezoneStrings["Europe/Isle_of_Man"],
  istanbul = TimezoneStrings["Europe/Istanbul"],
  jersey = TimezoneStrings["Europe/Jersey"],
  kaliningrad = TimezoneStrings["Europe/Kaliningrad"],
  kiev = TimezoneStrings["Europe/Kiev"],
  kirov = TimezoneStrings["Europe/Kirov"],
  lisbon = TimezoneStrings["Europe/Lisbon"],
  ljubljana = TimezoneStrings["Europe/Ljubljana"],
  london = TimezoneStrings["Europe/London"],
  luxembourg = TimezoneStrings["Europe/Luxembourg"],
  madrid = TimezoneStrings["Europe/Madrid"],
  malta = TimezoneStrings["Europe/Malta"],
  mariehamn = TimezoneStrings["Europe/Mariehamn"],
  minsk = TimezoneStrings["Europe/Minsk"],
  monaco = TimezoneStrings["Europe/Monaco"],
  moscow = TimezoneStrings["Europe/Moscow"],
  oslo = TimezoneStrings["Europe/Oslo"],
  paris = TimezoneStrings["Europe/Paris"],
  podgorica = TimezoneStrings["Europe/Podgorica"],
  prague = TimezoneStrings["Europe/Prague"],
  riga = TimezoneStrings["Europe/Riga"],
  rome = TimezoneStrings["Europe/Rome"],
  samara = TimezoneStrings["Europe/Samara"],
  san_marino = TimezoneStrings["Europe/San_Marino"],
  sarajevo = TimezoneStrings["Europe/Sarajevo"],
  simferopol = TimezoneStrings["Europe/Simferopol"],
  skopje = TimezoneStrings["Europe/Skopje"],
  sofia = TimezoneStrings["Europe/Sofia"],
  stockholm = TimezoneStrings["Europe/Stockholm"],
  tallinn = TimezoneStrings["Europe/Tallinn"],
  tirane = TimezoneStrings["Europe/Tirane"],
  ulyanovsk = TimezoneStrings["Europe/Ulyanovsk"],
  uzhgorod = TimezoneStrings["Europe/Uzhgorod"],
  vaduz = TimezoneStrings["Europe/Vaduz"],
  vatican = TimezoneStrings["Europe/Vatican"],
  vienna = TimezoneStrings["Europe/Vienna"],
  vilnius = TimezoneStrings["Europe/Vilnius"],
  volgograd = TimezoneStrings["Europe/Volgograd"],
  warsaw = TimezoneStrings["Europe/Warsaw"],
  zagreb = TimezoneStrings["Europe/Zagreb"],
  zaporozhye = TimezoneStrings["Europe/Zaporozhye"],
  zurich = TimezoneStrings["Europe/Zurich"],
  antananarivo = TimezoneStrings["Indian/Antananarivo"],
  chagos = TimezoneStrings["Indian/Chagos"],
  christmas = TimezoneStrings["Indian/Christmas"],
  cocos = TimezoneStrings["Indian/Cocos"],
  comoro = TimezoneStrings["Indian/Comoro"],
  kerguelen = TimezoneStrings["Indian/Kerguelen"],
  mahe = TimezoneStrings["Indian/Mahe"],
  maldives = TimezoneStrings["Indian/Maldives"],
  mauritius = TimezoneStrings["Indian/Mauritius"],
  mayotte = TimezoneStrings["Indian/Mayotte"],
  reunion = TimezoneStrings["Indian/Reunion"],
  apia = TimezoneStrings["Pacific/Apia"],
  auckland = TimezoneStrings["Pacific/Auckland"],
  bougainville = TimezoneStrings["Pacific/Bougainville"],
  chatham = TimezoneStrings["Pacific/Chatham"],
  chuuk = TimezoneStrings["Pacific/Chuuk"],
  easter = TimezoneStrings["Pacific/Easter"],
  efate = TimezoneStrings["Pacific/Efate"],
  enderbury = TimezoneStrings["Pacific/Enderbury"],
  fakaofo = TimezoneStrings["Pacific/Fakaofo"],
  fiji = TimezoneStrings["Pacific/Fiji"],
  funafuti = TimezoneStrings["Pacific/Funafuti"],
  galapagos = TimezoneStrings["Pacific/Galapagos"],
  gambier = TimezoneStrings["Pacific/Gambier"],
  guadalcanal = TimezoneStrings["Pacific/Guadalcanal"],
  guam = TimezoneStrings["Pacific/Guam"],
  honolulu = TimezoneStrings["Pacific/Honolulu"],
  johnston = TimezoneStrings["Pacific/Johnston"],
  kiritimati = TimezoneStrings["Pacific/Kiritimati"],
  kosrae = TimezoneStrings["Pacific/Kosrae"],
  kwajalein = TimezoneStrings["Pacific/Kwajalein"],
  majuro = TimezoneStrings["Pacific/Majuro"],
  marquesas = TimezoneStrings["Pacific/Marquesas"],
  midway = TimezoneStrings["Pacific/Midway"],
  nauru = TimezoneStrings["Pacific/Nauru"],
  niue = TimezoneStrings["Pacific/Niue"],
  norfolk = TimezoneStrings["Pacific/Norfolk"],
  noumea = TimezoneStrings["Pacific/Noumea"],
  pago_pago = TimezoneStrings["Pacific/Pago_Pago"],
  palau = TimezoneStrings["Pacific/Palau"],
  pitcairn = TimezoneStrings["Pacific/Pitcairn"],
  pohnpei = TimezoneStrings["Pacific/Pohnpei"],
  port_moresby = TimezoneStrings["Pacific/Port_Moresby"],
  rarotonga = TimezoneStrings["Pacific/Rarotonga"],
  saipan = TimezoneStrings["Pacific/Saipan"],
  tahiti = TimezoneStrings["Pacific/Tahiti"],
  tarawa = TimezoneStrings["Pacific/Tarawa"],
  tongatapu = TimezoneStrings["Pacific/Tongatapu"],
  wake = TimezoneStrings["Pacific/Wake"],
  wallis = TimezoneStrings["Pacific/Wallis"]
}

export type Timezones = TimezoneStrings | TZTimezones;
